baseURL = "/"
title = "openEuler documentation"

disablePathToLower = true

# Site language. Available translations in the theme's `/i18n` directory.
languageCode = "en-us"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
uglyURLs = true
buildFuture = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
# Define the number of posts per page
paginate = 10


[languages]
  [languages.en]
    languageCode = "en"
    contentDir = "content/en"
    [languages.en.params]
      rootSuffix = "openEuler documentation"
      suffix = "openEuler documentation"
  [languages.zh]
    languageCode = "zh"
    contentDir = "content/zh"
    [languages.zh.params]
      rootSuffix = "openEuler文档 | openEuler社区官网"
      suffix = "openEuler文档 | openEuler社区"


[params]
    resourceURL = "/"
    defaultKeywords = ["devows", "hugo", "go", "openEuler"]
    author = "Site template made by devcows Modified by openEuler team"
    defaultDescription = "Select the version and chapter of the openEuler documentation you want to view."
    email = "contact@openeuler.io"

    ### DOC Configurations
    BookEditPath= 'blob/master/content'
    BookDateFormat = 'Jan 2, 2019'
    enableGitInfo = true
    BookMenuBundle = '/menu'
    bookHidden = true
    bookFlatSection = true
    BookMenuBundleActiveLinkColor = '\#004ed0'
    showInnovation = true
    languageZh = "中文"
    languageEn = "English"

    ltsText = "LTS"
    version_88 = "23.03"
    version_89 = "22.03 LTS SP1"
    version_90 = "22.09"
    version_91 = "22.03 LTS"
    version_92 = "20.03 LTS SP3"
    version_93 = "21.09"
    version_94 = "20.03 LTS SP2"
    version_95 = "21.03"
    version_96 = "20.03 LTS SP1"
    version_97 = "20.09"
    version_98 = "20.03 LTS"


    notFound = "404"

